name: check
on: {workflow_dispatch, push: {branches: [main]}, pull_request}
jobs:
  nixpkgs-fmt:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - uses: cachix/install-nix-action@v31
      - run: nix develop -c nixpkgs-fmt --check .
  statix:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - uses: cachix/install-nix-action@v31
      - run: nix develop -c statix check
  deadnix:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - uses: cachix/install-nix-action@v31
      - run: nix develop -c deadnix -f -_ -l .
